language: csharp
mono: none
sudo: required
dist: focal
dotnet: 6.0.202
branches:
  only:
    - master
#    - develop
# Specify the version of Python to use

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - sudo apt-get install -y curl python3.8
  - python3.8 --version # Verificamos la versión de Python
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
  - python3 --version # Verificamos la versión de Python
  - pip3 install --upgrade pip
  - pip3 install virtualenv

install:
  # Configura el entorno virtual de Python
  - virtualenv -p python3.8 venv
  - source venv/bin/activate

  # Instala las dependencias de Python
  - curl https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=1 bash
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update --quiet
  - gcloud config set disable_prompts true

script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there    
    skip_cleanup: true
    keyfile: devops-dec-ci-cb5905623309.json
    project: devops-dec-ci
    version: polyglot
    default: true
    on:
        all_branches: true
# [END travis_deploy]